# Generated by Django 5.2.1 on 2025-06-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitlife', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FulName', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('Gender', models.CharField(max_length=10)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('DOB', models.DateField()),
                ('selectMembershipPlan', models.CharField(max_length=200)),
                ('SelectTrainer', models.CharField(max_length=20)),
                ('Refrence', models.CharField(max_length=20)),
                ('Address', models.TextField()),
                ('Time', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
